replicaCount: 1

ingress:
  host: bot.minikube

image:
  repository: localhost:5000
  pullSecret: registy-secret
  tag: latest

app:
  env: prod
  secret: app-secret-here
  telegram:
    bot_name: bot-name-here
    bot_token: secret-token-here-xxxxxxx
  database: "postgresql://db_user:db_pass@postgres:5432/db_name?serverVersion=11&charset=utf8"
  elastic:
    host: localhost
    port: 9200