---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: auth
    commands:
      - echo $DOCKER_PASSWORD | base64 -d | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
  - name: build
    commands:
      - docker build -t bot:latest --target prod .
  - name: publish
    commands:
      - docker tag bot:latest ${DOCKER_REGISTRY}/otmazki/bot:${DRONE_SEMVER}
      - docker push ${DOCKER_REGISTRY}/otmazki/bot:${DRONE_SEMVER}
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
#  - name: deploy
#    commands:
#      - helm upgrade bot .helm --set app.version=${DRONE_SEMVER} -f .helm/values.yaml --wait
#  - name: clear cache
#    commands:
#      - kubectl exec deployment/bot-fpm ./artisan -- cache:clear --tags excuses
#  - name: cleanup
#    commands:
#      - werf cleanup --images-repo gcr.io/learning-229721 --stages-storage :local  --git-tag-strategy-limit=-3
trigger:
  event:
    - tag
  branch:
    - master