kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: composer
  commands:
  - composer install
  - composer dump-autoload

- name: test
  image: php:7
  commands:
    - php vendor/phpunit/phpunit/phpunit

trigger:
  branch:
    - master
  event:
    - push
