---
kind: pipeline
type: kubernetes
name: quality

steps:
  - image: jakzal/phpqa:1.41.0
    name: lint
    commands:
      - php-cs-fixer fix ./src --dry-run
  - image: jakzal/phpqa:1.41.0
    name: unit-tests
    commands:
      - composer install
      - phpunit
trigger:
  event:
    - tag

---
kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: auth
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
  - name: build
    commands:
      - docker build -t bot:latest --target prod .
  - name: publish
    commands:
      - docker tag bot:latest $DOCKER_REGISTRY/otmazki/bot:${DRONE_SEMVER}
      - docker push $DOCKER_REGISTRY/otmazki/bot:${DRONE_SEMVER}
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
trigger:
  event:
    - tag

depends_on:
  - quality

---

kind: pipeline
type: kubernetes
name: deploy

steps:
  - name: deploy
    image: alpine/helm
    when:
      branch:
        - master
    commands:
      - helm upgrade $HELM_RELEASE_NAME ./chart --reuse-values --set image.tag=${DRONE_SEMVER} --recreate-pods --install --wait
    environment:
      HELM_RELEASE_NAME:
        from_secret: HELM_RELEASE_NAME

trigger:
  event:
    - tag

depends_on:
  - build
