version: '3.4'

services:

  php-fpm:
    build:
      context: ./
      target: dev
    volumes:
      - $PWD:/usr/app

  nginx:
    image: nginx:1.15.0
    ports:
      - 8080:8080
    volumes:
      - $PWD/.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf

volumes:
  elasticsearch:
  postgresql: