version: '3.4'

services:

  php-fpm:
    build:
      context: ./
      target: dev
    volumes:
      - $PWD:/usr/app

  nginx:
    image: nginx:1.15.0
    ports:
      - 8080:8080
    volumes:
      - $PWD/.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: 'db_name'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'db_pass'
    volumes:
      - postgresql:/var/lib/postgresql/data

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
#    container_name: 'elastic-search'
#    environment:
#      - discovery.type=single-node
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports:
#      - 9200:9200
#      - 9300:9300
#    working_dir: /app
#    volumes:
#      - ../:/app
#      - ./data/elasticsearch:/usr/share/elasticsearch/data

volumes:
  elasticsearch:
  postgresql: