version: '3.4'

services:

  php-fpm:
    build:
      context: ./
      target: dev
    volumes:
      - $PWD:/usr/app

  php-qa:
    image: jakzal/phpqa:1.41.0
    volumes:
      - $PWD:/usr/app
    working_dir: /usr/app

  nginx:
    image: nginx:1.15.0
    ports:
      - 8080:8080
    volumes:
      - $PWD/.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: 'db_name'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'db_pass'
    volumes:
      - postgresql:/var/lib/postgresql/data

  elasticsearch:
    build:
      context: ./
      dockerfile: .docker/elastic/Dockerfile
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  elasticsearch:
  postgresql:
