apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ingress-cm
data:
  SCRIPT_FILENAME: "/usr/app/public/index.php"

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: {{ .Release.Name }}-ingress-cm
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-bot-service
              servicePort: 9000