apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      restartPolicy: Never
      containers:
        - name: migrations
          image: '{{ .Values.image.repository }}/bot:{{ .Values.image.tag }}'
          command: [bin/console, doctrine:migrations:migrate, --no-interaction]
          env:
            - name: APP_ENV
              value: {{ .Values.app.env }}
            - name: DATABASE_URL
              value: {{ .Values.app.database | quote }}
