FROM elasticsearch:7.3.0

RUN bin/elasticsearch-plugin install analysis-icu
RUN bin/elasticsearch-plugin install https://github.com/papahigh/elasticsearch-keyboard-layout/raw/7.3.0/dist/keyboard-layout-7.3.0.zip