POST http://localhost:8080/telegram/webhook
Content-Type: application/json

{
  "update_id": 608774763,
  "message": {
    "message_id": 3128,
    "from": {
      "id": 126136035,
      "is_bot": false,
      "first_name": "Виктор",
      "username": "eW91IGFyZSBmYWdnb3Q",
      "language_code": "ru"
    },
    "chat": {
      "id": 126136035,
      "first_name": "Виктор",
      "username": "eW91IGFyZSBmYWdnb3Q",
      "type": "private"
    },
    "date": 1598389760,
    "text": "/random"
  }
}

###

POST http://localhost:8080/telegram/webhook
Content-Type: application/json

{
  "update_id": 608774766,
  "inline_query": {
    "id": "541750146164472345",
    "from": {
      "id": 126136035,
      "is_bot": false,
      "first_name": "Виктор",
      "username": "eW91IGFyZSBmYWdnb3Q",
      "language_code": "ru"
    },
    "query": "Hello",
    "offset": ""
  }
}

###
