apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ingress-cm
data:
  SCRIPT_FILENAME: "/app/build/public/index.php"
---

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: victor.lapshev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "{{ .Release.Name }}-ingress-cm"
spec:
  rules:
    - host: {{ .Values.app.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-fpm-service
              servicePort: 9000
  tls:
    - secretName: {{ .Release.Name }}-server-tls
      hosts:
        - {{ .Values.app.hostname }}
